language: android

android:
    components:
        - tools
        - build-tools-23.0.3
        - android-23
        - platform-tools-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

before_script:
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - "./gradlew clean assembleRelease"
    - "./gradlew cAT"
