language: android

dist: trusty

android:
    components:
        - tools
        - build-tools-28.0.3
        - android-27
        - android-21
        - sys-img-armeabi-v7a-android-21
        - platform-tools-28
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository
    licenses:
        - '.+'

before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
jdk:
    - oraclejdk8

script:
    - "./gradlew clean lint assembleRelease"
    - "android-wait-for-emulator"
    - "./gradlew cAT"
